-- models/FDR/initial_stage/TRANS_exp_DEFALUTS.sql
{{ config(materialized='table',
  tags=["FDR_m_ABC_AUDIT_WRKFL_RUN_ADD"]
) }}

WITH  SQ_FDR_LIB_FDWS_WORKFLOWS_V AS (
  SELECT *
  FROM {{ ref('stg_SQ_FDR_LIB_FDWS_WORKFLOWS_V') }}
),
lkp_lkp_FDR_LIB_ABC_CTRL_WRKFL_CMPNT_PRMTR_WRKFL_ID AS (
  SELECT
    WRKFL_ID,
    WRKFL_NM
  FROM {{ source('INFA_TGT', 'ABC_CTRL_WRKFL_PRMTR') }}
)

SELECT
  SQ_FDR_LIB_FDWS_WORKFLOWS_V.WORKFLOW_RUN_ID,
  lkp_lkp_FDR_LIB_ABC_CTRL_WRKFL_CMPNT_PRMTR_WRKFL_ID.WRKFL_ID AS o_WORKFLOW_ID,
  SQ_FDR_LIB_FDWS_WORKFLOWS_V.START_TIME,
  'Running' AS STATUS,
  {{ var("sess_name") }} AS var_SESS_NAME,
  {{ var('WORKFLOW_NAME') }} AS var_WORKFLOW_NAME,
  {{ var('FOLDER_NAME') }} AS var_FOLDER_NAME,
  {{ var("SERVER_NAME") }} AS var_SERVER_NAME,
  {{ var("SERVER_PORT") }} AS var_SERVER_PORT,
  {{ var("CONNECT_STRING") }} AS var_CONNECT_STRING,
  {{ var("DB_USER") }} AS var_DB_USER,
  {{ var("DB_PASSWORD") }} AS var_DB_PASSWORD
FROM
  SQ_FDR_LIB_FDWS_WORKFLOWS_V
  LEFT JOIN lkp_lkp_FDR_LIB_ABC_CTRL_WRKFL_CMPNT_PRMTR_WRKFL_ID
  ON lkp_lkp_FDR_LIB_ABC_CTRL_WRKFL_CMPNT_PRMTR_WRKFL_ID.WRKFL_NM = {{ var('WORKFLOW_NAME') }}
-- End-DBShift